### ISSUE TITLE
UserService를 짜는 도중 생긴 의문

### ISSUE THREAD

**Issue by youngkikim14** [youngkikim14/assignment2#1]
```
   @Transactional
     public void signup(SignupRequestDto signupRequestDto){
        String username = signupRequestDto.getUsername();
        String password = signupRequestDto.getPassword();

        Optional<User> found = userRepository.findByUsername(username);
        if (found.isPresent()){
            throw new IllegalArgumentException("중복 된 아이디입니다");
        }
       User user = new User(username, password);
        userRepository.save(user);
```
        

1. 중복된 아이디 처리 코드 중 if 문에 굳이 IllegalArgumentException가 쓰여야 하는 이유를 모르겠다.
이미 조건이 충족되었으니 그냥 중복된 아이디입니다 라고 메세지가 출력만 되면 끝나는거 아닌지?

2. 레포지토리에 저장하기 위해 user 객체를 하나 만들었는데 생성자 주입 DI로 객체 생성을 생략 해도 상관 없는지?

**Comment by Nhahan** [comment]
1. 프론트와의 협의가 되었다는 가정하에 메시지만 출력해도 됩니다. 그러나, 프론트 입장에서 보통은 메시지가 아니라 에러넘버(300 400 이런 숫자들. 예를 들어 특별한 에러처리가 필요하지 않은 경우 동일한 에러넘버를 주고 메시지를 다르게 할 수도 있음)로 예외처리를 하게 됩니다. 그리고 백엔드 입장에서도 남이 이런 코드를 볼 때 이게 '에러'라는 것도 중요한 포인트겠죠. 단순히 스트링만 리턴해버리면 협업을 할 때 "이거 뭐임..? 왜 스트링만 리턴함...? 뭐지?" 라고 생각할 수도 있겠죠. 이건 하나의 약속입니다. 200을 성공으로 하자, 300을 리다이렉트 혹은 뭐로 하자, 400 500은 무슨무슨 에러다(실무에선 예를 들어 300대를 그냥 임의로 예외처리로 쓰는 경우도 많음. 이것도 협의가 됐기에 가능한 것). 이렇게요. 하나의 예시를 더 들어볼까요. GET은 body를 가지지 않는다고 배우셨겠지만, 최근 스펙에선 GET도 body를 가질 수 있습니다. 따라서 GET만으로도 post put patch delete 등등...의 역할을 다 처리할 수 있습니다. GET으로 보내서 삭제해도 되잖아요? GET으로 보내서 수정해도 되잖아요? GET으로 보내서 등록해도 되잖아요? 하지만 그렇게 하지 않는건 일반적인 약속이기 때문입니다. 완벽하게 동일한 예시라고 보긴 어렵지만요.

2. 안됩니다. 스프링의 빈은 '싱글톤' 객체 입니다. User는 싱글톤이 아닙니다. 싱글톤은 그냥 1개만 있는거다라고 생각하시면 됩니다. User가 1명은 아니잖아요? A, B, C, D, E, F, G... 10억명의 유저가 있을 수도 있겠죠.

**Comment by youngkikim14** [comment]
감사합니다~! 의문 두개 전부 이해했습니다

**Comment by youngkikim14** [comment]
> 1. 프론트와의 협의가 되었다는 가정하에 메시지만 출력해도 됩니다. 그러나, 프론트 입장에서 보통은 메시지가 아니라 에러넘버(300 400 이런 숫자들. 예를 들어 특별한 에러처리가 필요하지 않은 경우 동일한 에러넘버를 주고 메시지를 다르게 할 수도 있음)로 예외처리를 하게 됩니다. 그리고 백엔드 입장에서도 남이 이런 코드를 볼 때 이게 '에러'라는 것도 중요한 포인트겠죠. 단순히 스트링만 리턴해버리면 협업을 할 때 "이거 뭐임..? 왜 스트링만 리턴함...? 뭐지?" 라고 생각할 수도 있겠죠. 이건 하나의 약속입니다. 200을 성공으로 하자, 300을 리다이렉트 혹은 뭐로 하자, 400 500은 무슨무슨 에러다(실무에선 예를 들어 300대를 그냥 임의로 예외처리로 쓰는 경우도 많음. 이것도 협의가 됐기에 가능한 것). 이렇게요. 하나의 예시를 더 들어볼까요. GET은 body를 가지지 않는다고 배우셨겠지만, 최근 스펙에선 GET도 body를 가질 수 있습니다. 따라서 GET만으로도 post put patch delete 등등...의 역할을 다 처리할 수 있습니다. GET으로 보내서 삭제해도 되잖아요? GET으로 보내서 수정해도 되잖아요? GET으로 보내서 등록해도 되잖아요? 하지만 그렇게 하지 않는건 일반적인 약속이기 때문입니다. 완벽하게 동일한 예시라고 보긴 어렵지만요.
> 2. 안됩니다. 스프링의 빈은 '싱글톤' 객체 입니다. User는 싱글톤이 아닙니다. 싱글톤은 그냥 1개만 있는거다라고 생각하시면 됩니다. User가 1명은 아니잖아요? A, B, C, D, E, F, G... 10억명의 유저가 있을 수도 있겠죠.

감사합니다~! 의문 두개 전부 이해했습니다
